### PR TITLE
Position and forward is not available in observed player data

### PR DESCRIPTION
**Pull request by NomisCZ**
Player: steamid: String, name: String, observer_slot: Number, team: 'CT' | 'T', activity: 'playing' | 'menu' | 'textinput'

### CODE REVIEW

**Comment by osztenkurden** [comment]
What is this PR even supposed to improve? You multiply declaration files for some reason, even though it's not necessary and you remove information about camera / observer?

**Comment by NomisCZ** [comment]
I only removed 'position' and 'forward' properties, which are not available in the observed player - https://github.com/osztenkurden/csgogsi/pull/8/files#diff-36d06484d7ee34fe8301c60f7c10c36e127d9893f4eb7fc442345854035cefe9L181

This causes a problem when calling the digest function. Changes in the lib directory is just a "build/transpile", npm run transpile.

```
"player": {
  "steamid": "XXXXXXXXXXXXXXXX",
  "name": "Player Name",
  "observer_slot": 1,
  "activity": "playing"
},
```

**Comment by osztenkurden** [comment]
This does cause a problem if GSI config doesn't have `player_position` set to 1, which I don't consider a valid case, because the whole package is created with dealing with everything in mind.
Regarding `.d.ts` files - they do not belong in lib/cjs and it seems like you use Windows terminal instead of Linux bash, because in transpile script are Linux-specific commands.
I do plan on making CSGOGSI object more configurable in the future, but for now I assume the GSI to send full data package, according to the following configuration:
```
"GSI"
{
	"uri"		"http://localhost:8080/"
	"timeout"		"0.1"
	"buffer"		"0"
	"throttle"		"0"
	"heartbeat"		"0.01"
	"data"
	{
		"provider"		"1"
		"map"		"1"
		"round"		"1"
		"player_id"		"1"
		"player_position"		"1"
		"player_state"		"1"
		"allplayers_id"		"1"
		"allplayers_state"		"1"
		"allplayers_match_stats"		"1"
		"allplayers_weapons"		"1"
		"allplayers_position"		"1"
		"allgrenades"		"1"
		"phase_countdowns"		"1"
		"map_round_wins"		"1"
		"bomb"		"1"
	}
}

```

**Comment by NomisCZ** [comment]
Oh, I missed that. Thanks for the info and sorry for the PR.

**Comment by osztenkurden** [comment]
No problem, I thought i broke something ;D

**Pull request closed without merging**
